setting:
  name: "test_oxford_spires_gs"
  output_root: "./pings_experiments"
  deskew: False
  color_channel: 3
  color_map_on: True
process:
  min_range_m: 1.0
  max_range_m: 80.0
  min_z_m: -10.0
  vox_down_m: 0.06
  dynamic_sdf_ratio_thre: 0.8
sampler:
  surface_sample_range_m: 0.25
  surface_sample_n: 6
  free_sample_begin_ratio: 0.5
  free_sample_end_dist_m: 0.6
  free_front_sample_n: 3 
  free_behind_sample_n: 1
neuralpoints:
  voxel_size_m: 0.2
  search_alpha: 0.5
  feature_dim: 32
  color_feature_dim: 16
  weighted_first: False
decoder:
  freeze_after_frame: 30
  gs_mlp_level: 1
  gs_mlp_hidden_dim: 128
loss:
  sigma_sigmoid_m: 0.05
  weight_color: 0.0
  ekional_loss_on: True
  numerical_grad: False
  weight_e: 0.2
continual:
  batch_size_new_sample: 1000
  pool_capacity: 2e7
  pool_filter_freq: 1
# tracker:
#   source_vox_down_m: 0.4
#   iter_n: 100
# pgo:
#   map_context: True
#   pgo_freq_frame: 30
gs:
  gs_type: gaussian_surfel # select from 3d_gs and gaussian_surfel
  exposure_correction_on: True
  view_concat_on: True
  cam_pose_train_on: True
  n_gaussian: 8
  gs_iters: 100
  gaussian_bs_ratio: 1.0
  img_pool_size: 80 
  long_term_img_pool_size: 320
  gs_down_rate: 1
  gs_vis_down_rate: 1
  gs_keyframe_accu_dist: 2.0
  lambda_depth: 0.01
  lambda_normal_depth: 0.01
  lambda_opacity: 5e-4 # 1e-3
  lambda_area: 1e-2
  consist_shift_count: 1
  lambda_sdf_cons: 0.05
  lambda_sdf_normal_cons: 0.05
  lambda_sdf: 1.0
  min_valid_nn_k: 3
  unit_scale_ratio: 0.2
  max_scale_ratio: 1.0
  displacement_range_ratio: 1.0
optimizer: # mapper
  iters: 15  # iterations per frame for sdf mapping
  batch_size: 16384
  learning_rate_geo: 2e-3
  learning_rate_color: 2e-3
  learning_rate_exposure: 1e-3
eval:
  mesh_freq_frame: 10 # reconstruct the mesh every x frames
  mesh_min_nn: 15
  mesh_default_on: True