setting: 
  name: "test_kitti_gs"
  output_root: "./pings_experiments"
  deskew: False
  kitti_correct: True
  correct_deg: 0.195
  color_channel: 3
  color_map_on: True 
process:
  min_range_m: 3.0
  max_range_m: 60.0 # 80.0
  min_z_m: -3.5
  vox_down_m: 0.05
sampler:
  surface_sample_range_m: 0.25
  surface_sample_n: 4
  free_sample_begin_ratio: 0.3
  free_sample_end_dist_m: 0.8
  free_front_sample_n: 2
  free_behind_sample_n: 1
neuralpoints:
  voxel_size_m: 0.25
  search_alpha: 0.8
  query_nn_k: 6
  feature_dim: 32
  color_feature_dim: 16
  weighted_first: False
decoder:
  freeze_after_frame: 30
  gs_mlp_hidden_dim: 128
loss:
  sigma_sigmoid_m: 0.05
  ekional_loss_on: True
  weight_e: 0.5
gs:
  gs_type: gaussian_surfel # select from 3d_gs and gaussian_surfel
  monodepth_on: True # False # If on, you need to install dependencies for the monodepth model
  exposure_correction_on: True
  cam_pose_train_on: False
  view_concat_on: True
  learn_color_residual: True
  gs_iters: 50 # 50
  gaussian_bs_ratio: 2.0
  img_pool_size: 20
  long_term_img_pool_size: 40
  gs_down_rate: 1
  gs_vis_down_rate: 1
  lambda_depth: 0.02
  lambda_normal_depth: 0.01
  lambda_mono_normal: 0.01
  lambda_opacity: 2e-3 # 5e-4 # increase to have more valid gaussians
  lambda_area: 1e-3
  lambda_sky: 1e-3
  consist_shift_count: 0
  lambda_sdf_cons: 0.02
  lambda_sdf_normal_cons: 0.02
  lambda_sdf: 0.5
continual:
  batch_size_new_sample: 2000
  pool_capacity: 1e7
  pool_filter_freq: 10
tracker:
  photo_loss: False
  source_vox_down_m: 0.6
  iter_n: 50
pgo:
  map_context: True
  pgo_freq_frame: 30
  context_cosdist: 0.3
  virtual_side_count: 10
  local_loop_dist_thre: 15.0
optimizer:
  batch_size: 8192
  iters: 15
  learning_rate_geo: 2e-3
  learning_rate_color: 2e-3
  learning_rate_exposure: 1e-3
eval:
  mesh_freq_frame: 10 # reconstruct the mesh every x frames
  mesh_min_nn: 9
  sensor_cad_path: ./cad/kitti_car.ply