setting:
  name: "test_oxford_spires_gs"
  output_root: "./pings_experiments"
  deskew: False
  color_channel: 3
  color_map_on: True
process:
  min_range_m: 1.0
  max_range_m: 60.0
  min_z_m: -10.0
  vox_down_m: 0.06
  # adaptive_range_on: True
  dynamic_sdf_ratio_thre: 0.8
sampler:
  surface_sample_range_m: 0.25
  surface_sample_n: 6
  free_sample_begin_ratio: 0.5
  free_sample_end_dist_m: 0.6
  free_front_sample_n: 3 
  free_behind_sample_n: 1
neuralpoints:
  voxel_size_m: 0.2
  search_alpha: 0.5
  query_nn_k: 6
  feature_dim: 32
  color_feature_dim: 8
  weighted_first: False
decoder:
  freeze_after_frame: 30
  gs_mlp_level: 1
  gs_mlp_hidden_dim: 128
loss:
  sigma_sigmoid_m: 0.05
  weight_color: 0.0
  loss_weight_on: False
  dist_weight_scale: 0.8
  ekional_loss_on: True
  numerical_grad: False
  weight_e: 0.1
continual:
  batch_size_new_sample: 1000
  pool_capacity: 2e7
  pool_filter_freq: 1
# tracker:
#   source_vox_down_m: 0.4
#   iter_n: 100
# pgo:
#   map_context: True
#   pgo_freq_frame: 30
gs:
  gs_type: gaussian_surfel # select from 3d_gs and gaussian_surfel
  exposure_correction_on: True
  view_concat_on: True
  dist_concat_on: False
  learn_color_residual: False
  cam_pose_train_on: False
  n_gaussian: 8
  gs_iters: 100
  gaussian_bs_ratio: 1.0
  img_pool_size: 40 
  long_term_img_pool_size: 120
  gs_down_rate: 1
  gs_keyframe_accu_dist: 1.0
  inverse_depth_loss: False
  lambda_depth: 0.01
  lambda_opacity: 1e-3
  lambda_area: 1e-4
  consist_shift_count: 1
  lambda_sdf_cons: 0.01
  lambda_sdf_normal_cons: 0.01
  lambda_sdf: 1.0
  min_alpha: 0.1
optimizer: # mapper
  iters: 15  # iterations per frame for sdf mapping
  batch_size: 16384
  learning_rate_geo: 0.002
  learning_rate_color: 0.002
  learning_rate_exposure: 1e-3
eval:
  gs_eval_on: False
  mesh_freq_frame: 10 # reconstruct the mesh every x frames
  mesh_min_nn: 14
  min_cluster_vertices: 1000